//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/PlayerScripts/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""InGames"",
            ""id"": ""eae3e5a1-c199-4e08-95d1-af5450f86c5d"",
            ""actions"": [
                {
                    ""name"": ""Move_keyboard"",
                    ""type"": ""Value"",
                    ""id"": ""4147b0d1-8778-4019-9c01-db6654c3be71"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move_gamepad"",
                    ""type"": ""Value"",
                    ""id"": ""98917108-2ee9-4d93-83cc-e9ca19eea736"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look_mouse"",
                    ""type"": ""Value"",
                    ""id"": ""f800f86e-f555-487f-9f0d-d97d27273bb0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look_gamepad"",
                    ""type"": ""Value"",
                    ""id"": ""d4c51da6-c4a3-4e39-a903-2fe2f4d15f5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""655e4a14-5295-4220-8297-079da14d3631"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""1b72f95f-9358-4480-99da-9a62bb03e09e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""a145d1a8-68d4-4b37-84c3-58fd15a8ce42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f82e8365-5726-4db2-b585-75d7eaa5242c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""8d78b085-4996-4e69-90f2-69e5c0070ec9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon Skill"",
                    ""type"": ""Button"",
                    ""id"": ""810c7bf2-fd59-472e-8046-dec1d53ba409"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Knock Back"",
                    ""type"": ""Button"",
                    ""id"": ""ff2a1525-06d8-4043-97ad-7af15efebefb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Item"",
                    ""type"": ""Button"",
                    ""id"": ""f87ea505-cde4-4d10-99df-6802476e552b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slime Throwing"",
                    ""type"": ""Button"",
                    ""id"": ""e1eaa71c-9325-475e-89a8-61b3a4e30254"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slime Shape"",
                    ""type"": ""Button"",
                    ""id"": ""4f81a2f0-6f3f-4982-88a0-b0e9e8edfed9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick Slot"",
                    ""type"": ""Value"",
                    ""id"": ""e00aafc5-c08b-4cea-81eb-abf32b100fa8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""327ac4e3-a413-42ee-9840-15a3e9b67332"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Look_mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""151b75dc-54da-4be0-afe8-a1d5c1c357d1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d43fab3-306f-4a7a-9c3f-8af52e51d997"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b03bac4-028f-4bdc-8b03-6865c10ab39f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf2dd031-f83f-44cb-a86a-7f6b691de505"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""123b8f06-87a2-450c-9618-f9add24a6364"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56e787d-56a9-4e4a-a9a9-90cb5cfb6232"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8f57d4a-ea6a-444d-b94d-ae8f60bbca29"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55020199-4345-4909-9bca-8474c6812bb7"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4250e892-9090-436c-adaa-d58d6e792f4c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c8c0f67-775c-4c17-ba2e-1dbad5829cec"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb885eb5-9a2d-40f2-9b7f-0f92bda2b1f2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Weapon Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8213f288-3ded-43b8-8d72-5e988f6beb51"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Weapon Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15557d87-91f5-4ac2-8506-011305f4687e"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Knock Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""817e957f-c088-405b-b175-e4713ae6dab7"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Knock Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f028fb26-729c-4f5d-ae8c-7e664f0523ae"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Use Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db41844f-e83d-47ab-8ae9-cdfe74fbff93"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Use Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca7928c0-1e2f-4599-a1ca-06cc771a4114"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Slime Throwing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dda63bd9-7940-4d5a-8621-1e6b45cc877d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Slime Throwing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""092e57e2-7c99-4a64-b410-e028e567b443"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Slime Shape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""030218ae-d680-4029-875f-bb882f970cb5"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Slime Shape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cf73c76-291c-48bc-a67a-8e779af41cc5"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Quick Slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0360c541-b042-437e-a144-a958946c0ada"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick Slot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""62422ee2-0f3b-480f-8da2-c113e34f19f0"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Quick Slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5222e590-7923-4dc9-ac28-d25c4e4bbd98"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Quick Slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e1b14217-76b9-4ada-a9c6-4c59d3215485"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Quick Slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f35204b4-3bde-43f9-9e7c-cf9ff5a1bf47"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Quick Slot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5002db6d-913e-4f83-9fd8-6fe1de4139b8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_keyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""83a4b1db-e25e-4903-aecc-c447b771831e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move_keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""38caa323-d2a8-4f16-8981-2584d264451e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move_keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""525ed8c4-fca6-4ab7-9d71-f94adc7e8fd4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move_keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4b870469-4ae8-4447-9c2c-e1e8169eb4ef"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move_keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""12ea3e60-3e5b-4538-a4be-de2b150f6988"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.2,max=0.96)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move_gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfbfba18-d08f-48dc-9c7e-804c74da84fb"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(max=0.98)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look_gamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InMenus"",
            ""id"": ""6a33efe0-658c-49ea-b003-08b055151a44"",
            ""actions"": [
                {
                    ""name"": ""MainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""69fb0333-ea8e-4917-8a06-2cd7efac0631"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GameMenu"",
                    ""type"": ""Button"",
                    ""id"": ""45ccc426-a9c1-4c65-bd9b-9623a0025a65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f5ba2ccf-1efd-4d73-a798-b496d2478aea"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""049f7809-a6e9-4a1c-97ce-09ea6c9b8d6c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86549984-0854-42be-ad9d-635e527c5b8c"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""GameMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""283ddd80-d8d4-45d2-a19b-23fa755e35d2"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""GameMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // InGames
        m_InGames = asset.FindActionMap("InGames", throwIfNotFound: true);
        m_InGames_Move_keyboard = m_InGames.FindAction("Move_keyboard", throwIfNotFound: true);
        m_InGames_Move_gamepad = m_InGames.FindAction("Move_gamepad", throwIfNotFound: true);
        m_InGames_Look_mouse = m_InGames.FindAction("Look_mouse", throwIfNotFound: true);
        m_InGames_Look_gamepad = m_InGames.FindAction("Look_gamepad", throwIfNotFound: true);
        m_InGames_Jump = m_InGames.FindAction("Jump", throwIfNotFound: true);
        m_InGames_Sprint = m_InGames.FindAction("Sprint", throwIfNotFound: true);
        m_InGames_Crouch = m_InGames.FindAction("Crouch", throwIfNotFound: true);
        m_InGames_Interact = m_InGames.FindAction("Interact", throwIfNotFound: true);
        m_InGames_Attack = m_InGames.FindAction("Attack", throwIfNotFound: true);
        m_InGames_WeaponSkill = m_InGames.FindAction("Weapon Skill", throwIfNotFound: true);
        m_InGames_KnockBack = m_InGames.FindAction("Knock Back", throwIfNotFound: true);
        m_InGames_UseItem = m_InGames.FindAction("Use Item", throwIfNotFound: true);
        m_InGames_SlimeThrowing = m_InGames.FindAction("Slime Throwing", throwIfNotFound: true);
        m_InGames_SlimeShape = m_InGames.FindAction("Slime Shape", throwIfNotFound: true);
        m_InGames_QuickSlot = m_InGames.FindAction("Quick Slot", throwIfNotFound: true);
        // InMenus
        m_InMenus = asset.FindActionMap("InMenus", throwIfNotFound: true);
        m_InMenus_MainMenu = m_InMenus.FindAction("MainMenu", throwIfNotFound: true);
        m_InMenus_GameMenu = m_InMenus.FindAction("GameMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGames
    private readonly InputActionMap m_InGames;
    private List<IInGamesActions> m_InGamesActionsCallbackInterfaces = new List<IInGamesActions>();
    private readonly InputAction m_InGames_Move_keyboard;
    private readonly InputAction m_InGames_Move_gamepad;
    private readonly InputAction m_InGames_Look_mouse;
    private readonly InputAction m_InGames_Look_gamepad;
    private readonly InputAction m_InGames_Jump;
    private readonly InputAction m_InGames_Sprint;
    private readonly InputAction m_InGames_Crouch;
    private readonly InputAction m_InGames_Interact;
    private readonly InputAction m_InGames_Attack;
    private readonly InputAction m_InGames_WeaponSkill;
    private readonly InputAction m_InGames_KnockBack;
    private readonly InputAction m_InGames_UseItem;
    private readonly InputAction m_InGames_SlimeThrowing;
    private readonly InputAction m_InGames_SlimeShape;
    private readonly InputAction m_InGames_QuickSlot;
    public struct InGamesActions
    {
        private @PlayerActions m_Wrapper;
        public InGamesActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move_keyboard => m_Wrapper.m_InGames_Move_keyboard;
        public InputAction @Move_gamepad => m_Wrapper.m_InGames_Move_gamepad;
        public InputAction @Look_mouse => m_Wrapper.m_InGames_Look_mouse;
        public InputAction @Look_gamepad => m_Wrapper.m_InGames_Look_gamepad;
        public InputAction @Jump => m_Wrapper.m_InGames_Jump;
        public InputAction @Sprint => m_Wrapper.m_InGames_Sprint;
        public InputAction @Crouch => m_Wrapper.m_InGames_Crouch;
        public InputAction @Interact => m_Wrapper.m_InGames_Interact;
        public InputAction @Attack => m_Wrapper.m_InGames_Attack;
        public InputAction @WeaponSkill => m_Wrapper.m_InGames_WeaponSkill;
        public InputAction @KnockBack => m_Wrapper.m_InGames_KnockBack;
        public InputAction @UseItem => m_Wrapper.m_InGames_UseItem;
        public InputAction @SlimeThrowing => m_Wrapper.m_InGames_SlimeThrowing;
        public InputAction @SlimeShape => m_Wrapper.m_InGames_SlimeShape;
        public InputAction @QuickSlot => m_Wrapper.m_InGames_QuickSlot;
        public InputActionMap Get() { return m_Wrapper.m_InGames; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGamesActions set) { return set.Get(); }
        public void AddCallbacks(IInGamesActions instance)
        {
            if (instance == null || m_Wrapper.m_InGamesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGamesActionsCallbackInterfaces.Add(instance);
            @Move_keyboard.started += instance.OnMove_keyboard;
            @Move_keyboard.performed += instance.OnMove_keyboard;
            @Move_keyboard.canceled += instance.OnMove_keyboard;
            @Move_gamepad.started += instance.OnMove_gamepad;
            @Move_gamepad.performed += instance.OnMove_gamepad;
            @Move_gamepad.canceled += instance.OnMove_gamepad;
            @Look_mouse.started += instance.OnLook_mouse;
            @Look_mouse.performed += instance.OnLook_mouse;
            @Look_mouse.canceled += instance.OnLook_mouse;
            @Look_gamepad.started += instance.OnLook_gamepad;
            @Look_gamepad.performed += instance.OnLook_gamepad;
            @Look_gamepad.canceled += instance.OnLook_gamepad;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @WeaponSkill.started += instance.OnWeaponSkill;
            @WeaponSkill.performed += instance.OnWeaponSkill;
            @WeaponSkill.canceled += instance.OnWeaponSkill;
            @KnockBack.started += instance.OnKnockBack;
            @KnockBack.performed += instance.OnKnockBack;
            @KnockBack.canceled += instance.OnKnockBack;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @SlimeThrowing.started += instance.OnSlimeThrowing;
            @SlimeThrowing.performed += instance.OnSlimeThrowing;
            @SlimeThrowing.canceled += instance.OnSlimeThrowing;
            @SlimeShape.started += instance.OnSlimeShape;
            @SlimeShape.performed += instance.OnSlimeShape;
            @SlimeShape.canceled += instance.OnSlimeShape;
            @QuickSlot.started += instance.OnQuickSlot;
            @QuickSlot.performed += instance.OnQuickSlot;
            @QuickSlot.canceled += instance.OnQuickSlot;
        }

        private void UnregisterCallbacks(IInGamesActions instance)
        {
            @Move_keyboard.started -= instance.OnMove_keyboard;
            @Move_keyboard.performed -= instance.OnMove_keyboard;
            @Move_keyboard.canceled -= instance.OnMove_keyboard;
            @Move_gamepad.started -= instance.OnMove_gamepad;
            @Move_gamepad.performed -= instance.OnMove_gamepad;
            @Move_gamepad.canceled -= instance.OnMove_gamepad;
            @Look_mouse.started -= instance.OnLook_mouse;
            @Look_mouse.performed -= instance.OnLook_mouse;
            @Look_mouse.canceled -= instance.OnLook_mouse;
            @Look_gamepad.started -= instance.OnLook_gamepad;
            @Look_gamepad.performed -= instance.OnLook_gamepad;
            @Look_gamepad.canceled -= instance.OnLook_gamepad;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @WeaponSkill.started -= instance.OnWeaponSkill;
            @WeaponSkill.performed -= instance.OnWeaponSkill;
            @WeaponSkill.canceled -= instance.OnWeaponSkill;
            @KnockBack.started -= instance.OnKnockBack;
            @KnockBack.performed -= instance.OnKnockBack;
            @KnockBack.canceled -= instance.OnKnockBack;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @SlimeThrowing.started -= instance.OnSlimeThrowing;
            @SlimeThrowing.performed -= instance.OnSlimeThrowing;
            @SlimeThrowing.canceled -= instance.OnSlimeThrowing;
            @SlimeShape.started -= instance.OnSlimeShape;
            @SlimeShape.performed -= instance.OnSlimeShape;
            @SlimeShape.canceled -= instance.OnSlimeShape;
            @QuickSlot.started -= instance.OnQuickSlot;
            @QuickSlot.performed -= instance.OnQuickSlot;
            @QuickSlot.canceled -= instance.OnQuickSlot;
        }

        public void RemoveCallbacks(IInGamesActions instance)
        {
            if (m_Wrapper.m_InGamesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGamesActions instance)
        {
            foreach (var item in m_Wrapper.m_InGamesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGamesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGamesActions @InGames => new InGamesActions(this);

    // InMenus
    private readonly InputActionMap m_InMenus;
    private List<IInMenusActions> m_InMenusActionsCallbackInterfaces = new List<IInMenusActions>();
    private readonly InputAction m_InMenus_MainMenu;
    private readonly InputAction m_InMenus_GameMenu;
    public struct InMenusActions
    {
        private @PlayerActions m_Wrapper;
        public InMenusActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MainMenu => m_Wrapper.m_InMenus_MainMenu;
        public InputAction @GameMenu => m_Wrapper.m_InMenus_GameMenu;
        public InputActionMap Get() { return m_Wrapper.m_InMenus; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InMenusActions set) { return set.Get(); }
        public void AddCallbacks(IInMenusActions instance)
        {
            if (instance == null || m_Wrapper.m_InMenusActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InMenusActionsCallbackInterfaces.Add(instance);
            @MainMenu.started += instance.OnMainMenu;
            @MainMenu.performed += instance.OnMainMenu;
            @MainMenu.canceled += instance.OnMainMenu;
            @GameMenu.started += instance.OnGameMenu;
            @GameMenu.performed += instance.OnGameMenu;
            @GameMenu.canceled += instance.OnGameMenu;
        }

        private void UnregisterCallbacks(IInMenusActions instance)
        {
            @MainMenu.started -= instance.OnMainMenu;
            @MainMenu.performed -= instance.OnMainMenu;
            @MainMenu.canceled -= instance.OnMainMenu;
            @GameMenu.started -= instance.OnGameMenu;
            @GameMenu.performed -= instance.OnGameMenu;
            @GameMenu.canceled -= instance.OnGameMenu;
        }

        public void RemoveCallbacks(IInMenusActions instance)
        {
            if (m_Wrapper.m_InMenusActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInMenusActions instance)
        {
            foreach (var item in m_Wrapper.m_InMenusActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InMenusActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InMenusActions @InMenus => new InMenusActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IInGamesActions
    {
        void OnMove_keyboard(InputAction.CallbackContext context);
        void OnMove_gamepad(InputAction.CallbackContext context);
        void OnLook_mouse(InputAction.CallbackContext context);
        void OnLook_gamepad(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnWeaponSkill(InputAction.CallbackContext context);
        void OnKnockBack(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnSlimeThrowing(InputAction.CallbackContext context);
        void OnSlimeShape(InputAction.CallbackContext context);
        void OnQuickSlot(InputAction.CallbackContext context);
    }
    public interface IInMenusActions
    {
        void OnMainMenu(InputAction.CallbackContext context);
        void OnGameMenu(InputAction.CallbackContext context);
    }
}
